[package]
name = "bran"
version = "0.1.0"
authors = ["raf"]

[dependencies]
webdriver_client = { git = "https://github.com/fluffysquirrels/webdriver_client_rust" }
mktemp = "0.3"
serde_json = "1.0"
base64 = "0.6"
clap = "2.0"
stderrlog = "0.2"
